name: Go Integration and Deployment

on: 
  push: 
    # make it a dev branch instead
    branches: [ dev ]

env:
  ECR_REGISTRY: ${{ secrets.VOLOMN_AWS_ECR_REGISTRY }}
  ECR_FRONTEND_REPOSITORY: voauth_web
  ECR_BACKEND_REPOSITORY: voauth_api


jobs: 
  build-push:
    name: Build and push docker images
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.VOLOMN_AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.VOLOMN_AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build Frontend Docker Image
      run: |
        cd frontend
        docker build -t $ECR_REGISTRY/$ECR_FRONTEND_REPOSITORY:$GITHUB_SHA .
        docker push $ECR_REGISTRY/$ECR_FRONTEND_REPOSITORY:$GITHUB_SHA
